### ISSUE TITLE
InternalServerError/Failed sync - "Couldn't upload assets"

### ISSUE THREAD

**Issue by shiftyscales** [Neos-Metaverse/NeosPublic#1822]
## Describe the bug
Some worlds appear to be having issues syncing for some users. Their UI will report everything as all synced, but they will always have unsynced records in their local database, and attempting to force the sync will fail with an InternalServerError.

## To Reproduce
- I do not have any specific replication steps unfortunately, but of the cases I've heard so far, each has been in relation to a world the user has created

## Expected behavior
- The synchronizing should either run as expected, or otherwise, should throw up a 'failed sync' warning on the sync facet

## Bug information (please complete the following information):
 - How often does it happen: Sometimes
 - Does the bug persist after restarting Neos? Yes
 - Neos Version: 2021.3.9.618
 - Neos Platform: Windows
 - Regression: Yes, I believe the first reported cases I've heard started occurring approximately two weeks ago

## Additional context
Logs have been submitted by various users on this issue including:
PlasmaRaven#5882:
https://cdn.discordapp.com/attachments/774060746894999610/814378266441941032/DESKTOP-E1MQ0LI_-_2021.2.22.855_-_2021-02-25_01_03_59.log

Elektrospy#0645:
https://cdn.discordapp.com/attachments/709757081754009600/817127490472509471/DESKTOP-CGLPPJS_-_2021.2.28.1210_-_2021-03-04_20_50_50.log

https://cdn.discordapp.com/attachments/709757081754009600/817128095781093407/DESKTOP-CGLPPJS_-_2021.2.28.1210_-_2021-03-04_21_05_48.log

https://cdn.discordapp.com/attachments/709757081754009600/817138043436924938/DESKTOP-CGLPPJS_-_2021.2.28.1210_-_2021-03-04_21_36_24.log

Honeypotbutt#9285:
https://cdn.discordapp.com/attachments/819326139016413234/819326213369102347/PCJUNI2020_-_2021.3.5.371_-_2021-03-08_21_11_26.log

https://cdn.discordapp.com/attachments/819326139016413234/819326216578007050/PCJUNI2020_-_2021.3.9.618_-_2021-03-10_21_37_19.log

The shared exception between them is the following:

```
9:40:37 PM.088 ( 60 FPS)	Upload failed: InternalServerError - 
9:40:37 PM.096 ( 60 FPS)	Failed sync for U-Elektrospy:R-d4792d1b-e449-45f9-a85c-bb6ebec540de. Local: 19, Global: 1:
Couldn't upload assets

   at void BaseX.UniLog.Error(string message, bool stackTrace)
   at void FrooxEngine.RecordUploadTask.Fail(string error)
   at async Task FrooxEngine.RecordUploadTask.RunUploadInternal(CancellationToken cancelationToken)
   at void System.Runtime.CompilerServices.AsyncMethodBuilderCore+MoveNextRunner.InvokeMoveNext(object stateMachine)
   at void System.Runtime.CompilerServices.AsyncMethodBuilderCore+MoveNextRunner.Run()
   at void System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction(Action action, bool allowInlining, ref Task currentTask)
   at void System.Threading.Tasks.Task.FinishContinuations()
   at void System.Threading.Tasks.Task.FinishStageThree()
   at bool System.Threading.Tasks.Task<CloudX.Shared.CloudResult<CloudX.Shared.AssetUploadData>>.TrySetResult(CloudResult<AssetUploadData> result)
   at void System.Runtime.CompilerServices.AsyncTaskMethodBuilder<CloudX.Shared.CloudResult<CloudX.Shared.AssetUploadData>>.SetResult(CloudResult<AssetUploadData> result)
   at async Task<CloudResult<AssetUploadData>> CloudX.Shared.CloudXInterface.BeginUploadAsset(string ownerId, string signature, string variant, string assetPath, int retries, IProgressIndicator progressIndicator, Nullable<long> bytes)
   at void System.Runtime.CompilerServices.AsyncMethodBuilderCore+MoveNextRunner.InvokeMoveNext(object stateMachine)
   at void System.Runtime.CompilerServices.AsyncMethodBuilderCore+MoveNextRunner.Run()
   at void System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction(Action action, bool allowInlining, ref Task currentTask)
   at void System.Threading.Tasks.Task.FinishContinuations()
   at void System.Threading.Tasks.Task.FinishStageThree()
   at bool System.Threading.Tasks.Task<CloudX.Shared.CloudResult<CloudX.Shared.AssetUploadData>>.TrySetResult(CloudResult<AssetUploadData> result)
   at void System.Runtime.CompilerServices.AsyncTaskMethodBuilder<CloudX.Shared.CloudResult<CloudX.Shared.AssetUploadData>>.SetResult(CloudResult<AssetUploadData> result)
   at async Task<CloudResult<AssetUploadData>> CloudX.Shared.CloudXInterface.BeginUploadAsset(string ownerId, string signature, string variant, Stream fileStream, string fileName, int retries, IProgressIndicator progressIndicator, Nullable<long> bytes)
   at void System.Runtime.CompilerServices.AsyncMethodBuilderCore+MoveNextRunner.InvokeMoveNext(object stateMachine)
   at void System.Runtime.CompilerServices.AsyncMethodBuilderCore+MoveNextRunner.Run()
   at void System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction(Action action, bool allowInlining, ref Task currentTask)
   at void System.Threading.Tasks.Task.FinishContinuations()
   at void System.Threading.Tasks.Task.FinishStageThree()
   at bool System.Threading.Tasks.Task<CloudX.Shared.CloudXInterface+UploadChunkBuffer>.TrySetResult(UploadChunkBuffer result)
   at void System.Runtime.CompilerServices.AsyncTaskMethodBuilder<CloudX.Shared.CloudXInterface+UploadChunkBuffer>.SetResult(UploadChunkBuffer result)
   at async Task<UploadChunkBuffer> CloudX.Shared.CloudXInterface.TakeFinishedBuffer(List<UploadChunkBuffer> buffers)
   at void System.Runtime.CompilerServices.AsyncMethodBuilderCore+MoveNextRunner.InvokeMoveNext(object stateMachine)
   at void System.Runtime.CompilerServices.AsyncMethodBuilderCore+MoveNextRunner.Run()
   at void System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction(Action action, bool allowInlining, ref Task currentTask)
   at void System.Threading.Tasks.Task.FinishContinuations()
   at void System.Threading.Tasks.Task.FinishStageThree()
   at bool System.Threading.Tasks.Task<System.Threading.Tasks.Task>.TrySetResult(Task result)
   at void System.Threading.Tasks.TaskFactory+CompleteOnInvokePromise.Invoke(Task completingTask)
   at void System.Threading.Tasks.Task.FinishContinuations()
   at void System.Threading.Tasks.Task.FinishStageThree()
   at bool System.Threading.Tasks.Task<CloudX.Shared.CloudResult>.TrySetResult(CloudResult result)
   at void System.Runtime.CompilerServices.AsyncTaskMethodBuilder<CloudX.Shared.CloudResult>.SetResult(CloudResult result)
   at async Task<CloudResult> CloudX.Shared.CloudXInterface.RunRequest(Func<HttpRequestMessage> requestSource, Nullable<TimeSpan> timeout, bool throwOnError)
   at void System.Runtime.CompilerServices.AsyncMethodBuilderCore+MoveNextRunner.InvokeMoveNext(object stateMachine)
   at void System.Runtime.CompilerServices.AsyncMethodBuilderCore+MoveNextRunner.Run()
   at void System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction(Action action, bool allowInlining, ref Task currentTask)
   at void System.Threading.Tasks.Task.FinishContinuations()
   at void System.Threading.Tasks.Task.FinishStageThree()
   at bool System.Threading.Tasks.Task<CloudX.Shared.CloudResult<string>>.TrySetResult(CloudResult<string> result)
   at void System.Runtime.CompilerServices.AsyncTaskMethodBuilder<CloudX.Shared.CloudResult<string>>.SetResult(CloudResult<string> result)
   at async void CloudX.Shared.CloudXInterface+<RunRequest>d__189<string>.MoveNext()
   at void System.Runtime.CompilerServices.AsyncMethodBuilderCore+MoveNextRunner.InvokeMoveNext(object stateMachine)
   at void System.Runtime.CompilerServices.AsyncMethodBuilderCore+MoveNextRunner.Run()
   at void System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction(Action action, bool allowInlining, ref Task currentTask)
   at void System.Threading.Tasks.Task.FinishContinuations()
   at void System.Threading.Tasks.Task.FinishStageThree()
   at bool System.Threading.Tasks.Task<System.Threading.Tasks.VoidTaskResult>.TrySetResult(VoidTaskResult result)
   at void System.Threading.Tasks.Task+DelayPromise.Complete()
   at Task System.Threading.Tasks.Task.Delay(TimeSpan delay)+(object state) => { }
   at void System.Threading.Timer+Scheduler.TimerCB(object o)
   at void System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at bool System.Threading.ThreadPoolWorkQueue.Dispatch()
   at bool System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()
```

## Reporters:
PlasmaRaven#5882, Elektrospy#0645, Honeypotbutt#9285, Shifty#7944

**Comment by Frooxius** [comment]
I've checked the server side logs, but this looks like a problem with the user's connection. All the requests to upload the asset data got suddenly interrupted, which is why the cloud responded with 500 (it threw BadHttpRequestException at its end). I've checked PlasmaRaven's logs before and their connection was randomly interrupting. From what I was told, they fixed their router which has resolved the issue. Is that correct? Or are they still experiencing problem?

There's not too much we can do to deal with faulty connections. Neos has a retry logic that attempt to reupload, but there's only so much that can do with problematic connection. Some of the logs were too old for me to check and didn't turn up anything unfortunately, if there are any more recent cases let me know.

I'll check why it doesn't show that the sync has failed, so the user is at least informed.

**Comment by shiftyscales** [comment]
In Raven's case, last I heard they were still having issues.

In Elektrospy's case, he reported to me:
> Heyho Shifty, small update regarding the Uploading of my map update.
I finally was able to do the sync, but its a pretty janky workaround
we needed to split the whole hierarchy in neos, for all the child objects and upload the "chunks" individually
after that remerge everything and save over
so my guess is, that i had run out of json character space on the serialisation, which made it fail while parsing

I'll let you know if I can get any more up to date logs/additional information. The peculiar thing about these cases is the sync facet as noted. It has led to confusion from some users about the content they saved/uploaded disappearing from their inventories since it was never fully synced, but was reported as all synced.

Thanks, @Frooxius!

**Comment by Electronus** [comment]
@Frooxius My understanding is that Plasma though it was fixed and reported it was to me(and I passed to you), and I saw him in the discord the next day with the same issues. I should have notified, sorry about that just got busy.

**Comment by Frooxius** [comment]
Build 2021.3.12.44 now will correctly report that the sync has failed when it does.

@shiftyscales That workaround definitely isn't what made it work, because it doesn't make technical sense, it's not how this process works or something that would be a limitation. From what I can tell the connection when uploading the binary data (there's no JSON involved there at all) drops for some reason, which makes the cloud end throw the error.

The retry logic should take care of that though and just try again, I'll have a deeper look to see if there's something odd there, but I can tell you it's definitely not what they're assuming it is.

**Comment by shiftyscales** [comment]
Hey @Frooxius. Got a couple of fresh logs from Honey.

https://cdn.discordapp.com/attachments/819326139016413234/820418728268398612/PCJUNI2020_-_2021.3.12.44_-_2021-03-13_22_59_44.log

Trying to use `-ForceSyncConflictingCloudRecords` fails to resolve the issue/the assets still can't be uploaded:
https://cdn.discordapp.com/attachments/819326139016413234/820423565224443954/PCJUNI2020_-_2021.3.12.44_-_2021-03-13_23_14_27.log

**Comment by Frooxius** [comment]
Thanks! It still looks like they have some networking error, with the connection randomly dropping. The weird thing is that it doesn't seem to invoke the retry logic on it, normally Neos will try the same request a few times, since these types of errors are typically intermittent. 

I have enabled detailed diagnostics for all three accounts (PlasmaRaven, Elektrospy and Honey), could you send me fresh logs from any of these if they encounter the problem again?

**Comment by shiftyscales** [comment]
Sure thing. I'll pass on the info. Thanks Froox.

**Comment by xXFaZeGaMeR900Xx** [comment]
last i was on Neos vr before i got this error measge saying check log i wasn't having issues with stuff diapering from my inventory but then evently it will do it again but when i mess with my saved folders for the cache etc i think it completely puts me back where i can save stuff with out diapering stuff keep in mind my inventory even says all synced but then when i got out of Neos and go back in and checked my folder where i saved the avatar boom i watch it disappear also forgot to mention for example when i moved the location to another drive before i did that stuff was diapering from my inventory once i change locations on both folders didnt have the issue again

**Comment by xXFaZeGaMeR900Xx** [comment]
i hope that made sense and helped anyone

**Comment by TehTurk** [comment]
Would it be possible for the Errors to reflect what the code is then on the facet? Usually depending on the code you can kinda infer for the user and they have an idea on what's going on, and they can resolve it or note it down as a non-issue.

**Comment by Frooxius** [comment]
The errors are too verbose to be included in the facet and there might be multiple. At some point I plan to add UI what will show all the active syncs and any failed ones, with UI to resolve the conflicts in-game or view detailed information on what failed.

I have a fix coming in the next build that should significantly improve robustness. Turns out, that the request retry logic wouldn't trigger in most cases, making the whole process break on a single intermittent connection problem.

**Comment by xXFaZeGaMeR900Xx** [comment]
ok but i just saw my name on the last update for the RecordSyncStatus im shocked that didnt help me in anyway

**Comment by Frooxius** [comment]
Ok fix is out in 2021.3.16.1287! This should make the sync process much more robust, as well as any other API requests, by actually retrying the upload and any other requests in case of intermittent server/connection problems or overload.
